- id: prettier
  name: Prettier
  entry: prettier --check
  language: node
  exclude: ^.+lock\.\w+$
  types_or:
    - javascript
    - jsx
    - ts
    - tsx
    - css
    - html
    - json
    - yaml
    - vue
  description: Check code style with prettier
  additional_dependencies:
    - prettier@3.3.3

- id: eslint
  name: ESLint
  entry: eslint
  language: node
  types_or:
    - javascript
    - jsx
    - ts
    - tsx
    - vue
  description: Lint code with eslint
  additional_dependencies:
    - eslint@9.8.0

- id: vitest
  name: Vitest
  entry: vitest run
  language: node
  types:
    - text
  files: ^.+\.(?:jsx?|tsx?|vue|css|html)$|package\.json$
  pass_filenames: false
  description: Run tests with vitest
  additional_dependencies:
    - vitest@2.0.5
