- id: prettier
  name: Prettier
  entry: prettier --check
  language: node
  exclude: ^.+lock\.\w+$
  types_or:
    - javascript
    - jsx
    - ts
    - tsx
    - css
    - html
    - json
    - yaml
    - vue
  description: Check code style with prettier
  additional_dependencies:
    - prettier@3.3.3

- id: eslint
  name: ESLint
  entry: eslint
  language: node
  types_or:
    - javascript
    - jsx
    - ts
    - tsx
    - vue
  description: Lint code with eslint
  additional_dependencies:
    - eslint@9.8.0
