- id: gofmt
  name: gofmt
  entry: gofmt -s -w
  language: golang
  types:
    - go
    - go-mod
    - go-sum
  description: Run gofmt on modified Go files

- id: prettier
  name: prettier
  entry: prettier --check
  language: node
  exclude: ^.+lock\.\w+$
  types_or:
    - javascript
    - jsx
    - ts
    - tsx
    - css
    - html
    - json
    - yaml
    - vue
  description: Check code style with prettier
  additional_dependencies:
    - prettier@3.3.3
